### ISSUE TITLE
hack/update-codegen.sh uses deprecated scripts

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#1196] opened 2023-10-11 18:07 UTC
**What would you like to be cleaned**:

When running `make generate`, this message shows up:

```
WARNING: generate-groups.sh is deprecated.
WARNING: Please use k8s.io/code-generator/kube_codegen.sh instead.

WARNING: generate-internal-groups.sh is deprecated.
WARNING: Please use k8s.io/code-generator/kube_codegen.sh instead.
```

**Why is this needed**:

Keep kueue building

**Comment by kannon92** [comment] 2023-10-12 00:07
I think https://github.com/kubernetes-sigs/kueue/pull/1151/files should resolve this

**Comment by kannon92** [comment] 2023-10-12 00:07
Maybe this ticket is a duplicate of https://github.com/kubernetes-sigs/kueue/issues/1134

**Comment by tenzen-y** [comment] 2023-10-12 05:32
> Maybe this ticket is a duplicate of https://github.com/kubernetes-sigs/kueue/issues/1134

Yes, that's right.
/close

**Closed by tenzen-y** 2023-10-12 05:32 UTC
Labels: kind/cleanup
