### ISSUE TITLE
Flaky e2e MultiKueue test

### ISSUE THREAD

**Issue by PBundyra** [kubernetes-sigs/kueue#3718] opened 2024-12-03 10:40 UTC
**What happened**:
E2e MultiKueue test failed

**What you expected to happen**:
No failure

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/3708/pull-kueue-test-multikueue-e2e-main/1863892287004610560

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by PBundyra** [comment] 2024-12-03 10:40
cc @mbobrovskyi

**Comment by mbobrovskyi** [comment] 2024-12-03 10:58
/close

Duplicate of https://github.com/kubernetes-sigs/kueue/issues/3581.

**Closed by mbobrovskyi** 2024-12-03 10:58 UTC
Labels: kind/bug
