### ISSUE TITLE
Vendored JobSet does not have Coordinator field in v0.8.0-

### ISSUE THREAD

**Issue by avrittrohwer** [kubernetes-sigs/kueue#3495] opened 2024-11-08 18:15 UTC
**What happened**:

Seen in https://github.com/kubernetes-sigs/jobset/issues/701.  When using JobSet and Kueue in the same cluster, Kueue needs to be at v0.9.0+ for the JobSet Coordinator field to not be nilled by the Kueue JobSet mutating webhook.

**What you expected to happen**:

Kueue mutating webhook does not remove valid JobSet fields.

**How to reproduce it (as minimally and precisely as possible)**:

Install kueue v0.8.0 and JobSet v0.7.0 in a cluster.  Create a JobSet with a non-nil Coordinator field.  The Kueue mutating webhook will cause the JobSet to be created with a nil Coordinator field.

**Anything else we need to know?**:

Kueue v0.9.0 is the first version with a copy of jobset API with coordinator field: https://github.com/kubernetes-sigs/kueue/blob/release-0.9/vendor/sigs.k8s.io/jobset/api/jobset/v1alpha2/jobset_types.go

v0.8.0 does not have the field: https://github.com/kubernetes-sigs/kueue/blob/release-0.8/vendor/sigs.k8s.io/jobset/api/jobset/v1alpha2/jobset_types.go

**Environment**:
- Kubernetes version (use `kubectl version`): 1.31
- Kueue version (use `git describe --tags --dirty --always`): v0.8.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mimowo** [comment] 2024-11-08 19:08
0.8.3 should have the fix

**Comment by avrittrohwer** [comment] 2024-11-08 19:38
> 0.8.3 should have the fix. ptal https://github.com/kubernetes-sigs/kueue/releases/tag/v0.8.3

https://github.com/kubernetes-sigs/kueue/blob/v0.8.3/vendor/sigs.k8s.io/jobset/api/jobset/v1alpha2/jobset_types.go#L65 does not have Coordinator field

**Comment by mimowo** [comment] 2024-11-08 19:44
right, but if the root cause is that kueue webhook drops unknown field then this is fixed in 0.8.2 by a change to prevent dropping unknown fields; https://github.com/mimowo/kueue/blob/main/CHANGELOG%2FCHANGELOG-0.8.md

**Comment by avrittrohwer** [comment] 2024-11-08 19:46
Ah I see

**Comment by avrittrohwer** [comment] 2024-11-08 19:48
Updated https://github.com/kubernetes-sigs/jobset/pull/702 with the fixed v0.8.3+ version

**Comment by avrittrohwer** [comment] 2024-11-08 20:26
For any other fixed versions please update https://github.com/kubernetes-sigs/jobset/blob/main/site/content/en/docs/concepts/_index.md?plain=1#L204

**Comment by mimowo** [comment] 2024-11-12 08:11
/close 
I think this issue is no longer actionable. The new JobSet field can be used in 0.8.3+ and 0.9.0+.

**Closed by mimowo** 2024-11-12 08:11 UTC
Labels: kind/bug
