### ISSUE TITLE
support deployment object

### ISSUE THREAD

**Issue by inforly** [kubernetes-sigs/kueue#2237] opened 2024-05-20 12:49 UTC
**What would you like to be added**:
Can Kueue add the support to K8s deployment object, so that the online services (deployments) can work together with the offline jobs together under one namespace. 

**Why is this needed**:
Usually, one namespace has both online services and offline jobs running, so needs a unified queue system to manage the resource and the scheduling, then the features like deployment autoscaling/preemption can be implemented based on this, without blocking by the resource quota (admission controller).

**Completion requirements**:

This enhancement requires the following artifacts:

- [*] Design doc
- [*] API change
- [*] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment] 2024-05-22 14:31
Can you clarify what your expectations are in terms of atomicity?

Should all pods of the Deployment be admitted at the same time? If not, the pod integration might be a good way to Kueue support services today.

Also see #635

**Comment by alculquicondor** [comment] 2024-06-25 21:00
/close
Duplicate of #867

**Closed by alculquicondor** 2024-06-25 21:00 UTC
Labels: kind/feature
