### ISSUE TITLE
Flaky scheduler integration test

### ISSUE THREAD

**Issue by PBundyra** [kubernetes-sigs/kueue#3679] opened 2024-11-28 14:18 UTC
**What happened**:
Scheduler integration test failed

**What you expected to happen**:
No failure

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/3677/pull-kueue-test-integration-main/1862134281669709824

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by gabesaba** [comment] 2024-12-04 10:19
/close
duplicate of #3633

**Closed by gabesaba** 2024-12-04 10:20 UTC
Labels: kind/bug
