### ISSUE TITLE
Kueue integration tests are marked failed consistently in the testgrid

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#2148] opened 2024-05-07 10:04 UTC
**What happened**:

The integration tests (both periodic and pull) are marked failed:

https://testgrid.k8s.io/sig-scheduling#periodic-kueue-test-integration-main

![image](https://github.com/kubernetes-sigs/kueue/assets/10359181/80df3ef2-94cb-45c7-9e32-32bba19d7ac9)

https://testgrid.k8s.io/sig-scheduling#pull-kueue-test-integration-main:

![image](https://github.com/kubernetes-sigs/kueue/assets/10359181/d2683c2e-0b8f-4620-94f8-8d6d55e89b58)

Even though all tests are reported as succeeded inside.

**What you expected to happen**:

The tests are reported as successful (green)

**Comment by gabesaba** [comment] 2024-05-07 11:14
duplicate of https://github.com/kubernetes-sigs/kueue/issues/2097

**Closed** 2024-05-07 11:21 UTC
Labels: kind/bug
