### ISSUE TITLE
Flaky integration test: " Pod controller when manageJobsWithoutQueueName is disabled when Using pod group Should keep the running pod group with the queue name if workload is evicted"

### ISSUE THREAD

**Issue by PBundyra** [kubernetes-sigs/kueue#2257] opened 2024-05-22 13:17 UTC
/kind flake

**What happened**:
Integration test of the pod controller failed

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2255/pull-kueue-test-integration-main/1793264698469126144

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by trasc** [comment] 2024-05-22 14:20
/close 
duplicate of #2243

**Closed by trasc** 2024-05-22 14:20 UTC
Labels: kind/bug, kind/flake
